In [5]:
a=[1,20,21,34,56,71,0]
a.sort()
print(a[3:6])

[21, 34, 56]


In [10]:
i=1
mul=1
for i in range(1,10):
    mul=i*mul
    
print(mul)

def factorial(n): 
    return 1 if(n==0 or n==1) else n* factorial(n-1)  

factorial(9)

362880


362880

In [13]:
a=[11,12,23,21,34,22]
for i in a:
    print("even") if(i%2==0)else print("odd")

odd
even
odd
odd
even
even


In [17]:
import numpy as np
a=np.linspace(1,7,100) # from 1 to 7

a[a<1.3030303]

array([1.        , 1.06060606, 1.12121212, 1.18181818, 1.24242424])

In [26]:
a=np.random.randint(10,100,25).reshape(5,5)
count=0
for i in a:
    i[count+1:]=0
    count+=1
    
    print(i)
    

[50  0  0  0  0]
[40 91  0  0  0]
[80 95 26  0  0]
[82 16 35 51  0]
[89 86 52 95 69]
